---
# tasks file for roles/xps
- name: Install XPS packages
  dnf:
    name: "{{ lookup('flattened', item) }}"
    state: present
  become: yes
  with_items: [] # TODO: if there are any XPS-specific packages anymore, add them here

