source 'https://supermarket.chef.io'

metadata

cookbook 'docker', '~> 2.15.2'

# Do various things with Python
cookbook 'poise-python', '~> 1.5.1'

# IntelliJ IDEA installer
cookbook 'idea', '~> 0.6.0'

cookbook 'java', '~> 1.48.0'
